name: embrace_hackathon
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dart_openai: ^5.1.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  path: ^1.9.1
  file_picker: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env